<link rel="stylesheet" href="<?=$this->baseUrl?>css/style.css">
    <link rel="stylesheet" href="<?=$this->baseUrl?>css/bootstrap-grid.css">
    <link rel="stylesheet" href="<?=$this->baseUrl?>css/bootstrap.css">
    <link rel="stylesheet" href="<?=$this->baseUrl?>jquery/jquery.css">
   


</body>
</html>
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active px-lg-4">
		  <a class="nav-link" href="<?=$this->baseUrl?>home">home<span class="sr-only">(current)</span></a>
            </a>
          </li>
          <li class="nav-item px-lg-4">
		  <a class="nav-link" href="<?=$this->baseUrl?>dieren">dieren<span class="sr-only">(current)</span></a>
		  </li>
		  <li class="nav-item px-lg-4">
		  <a class="nav-link" href="<?=$this->baseUrl?>products">producten<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item px-lg-4">
		  <a class="nav-link" href="<?=$this->baseUrl?>diereninformatie">dieren informatie<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item px-lg-4">
		  <a class="nav-link" href="<?=$this->baseUrl?>overons">over ons <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item px-lg-4">
		  <a class="nav-link" href="<?=$this->baseUrl?>login">login<span class="sr-only">(current)</span></a>
		  </li>
		  <li class="nav-item px-lg-4">
		  <a class="nav-link" href="<?=$this->baseUrl?>contact">contact<span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>